import React, { useState } from "react"
import { Box, Muted, Small, Text, TextInput, useBoxRect } from "silvery"
import type { Controller, SessionHandle } from "../controller.ts"

/**
 * Per-agent display label. Mirrors the `AGENT_DISPLAY` map in `SidePanel.tsx`
 * so the welcome card and the side-panel branding row stay in sync. Unknown
 * agent id → bare "Silver Code". Bead: km-silvercode.welcome-claude-hardcoded.
 */
const AGENT_LABELS: Readonly<Record<string, string>> = {
  "claude-code": "Claude Code",
  "claude-code-spawn": "Claude Code",
  "claude-code-sdk": "Claude Code",
  codex: "Codex",
  "codex-spawn": "Codex",
  gemini: "Gemini",
  "github-copilot-cli": "GitHub Copilot",
}

/*
 * SILVER / CODE figlet block letters (pre-generated, NOT runtime-rendered).
 *
 * Generated with `figlet` so the per-row character alignment is correct
 * (LLMs reliably misalign hand-rolled multi-line ASCII art — see memory:
 * `feedback-no-box-diagrams`). Pasted as a string-literal constant so the
 * app has no runtime dep on figlet and the lines are immutable.
 *
 * To regenerate (output is deterministic for the given font + word):
 *   figlet -f standard "SILVER"
 *   figlet -f standard "CODE"
 *   figlet -f small    "SILVER"
 *   figlet -f small    "CODE"
 *
 * Width measurements (load-bearing for the narrow-width fallback below):
 *   standard SILVER: 33 cols × 5 rows
 *   standard CODE:   24 cols × 5 rows
 *   small    SILVER: 26 cols × 4 rows
 *   small    CODE:   20 cols × 4 rows
 *
 * Bead: km-cr94.
 */

// generated by: figlet -f standard "SILVER"
const SILVER_STANDARD: ReadonlyArray<string> = [
  " ____ ___ _ __     _______ ____  ",
  "/ ___|_ _| |\\ \\   / / ____|  _ \\ ",
  "\\___ \\| || | \\ \\ / /|  _| | |_) |",
  " ___) | || |__\\ V / | |___|  _ < ",
  "|____/___|_____\\_/  |_____|_| \\_\\",
]

// generated by: figlet -f standard "CODE"
const CODE_STANDARD: ReadonlyArray<string> = [
  "  ____ ___  ____  _____ ",
  " / ___/ _ \\|  _ \\| ____|",
  "| |  | | | | | | |  _|  ",
  "| |__| |_| | |_| | |___ ",
  " \\____\\___/|____/|_____|",
]

// generated by: figlet -f small "SILVER"
const SILVER_SMALL: ReadonlyArray<string> = [
  " ___ ___ _ __   _____ ___ ",
  "/ __|_ _| |\\ \\ / / __| _ \\",
  "\\__ \\| || |_\\ V /| _||   /",
  "|___/___|____\\_/ |___|_|_\\",
]

// generated by: figlet -f small "CODE"
const CODE_SMALL: ReadonlyArray<string> = [
  "  ___ ___  ___  ___ ",
  " / __/ _ \\|   \\| __|",
  "| (_| (_) | |) | _| ",
  " \\___\\___/|___/|___|",
]

/** Min container width for each tier (cols). Below SMALL_MIN, fall back to stacked text. */
const STANDARD_MIN_COLS = 36
const SMALL_MIN_COLS = 28

type BannerTier = "standard" | "small" | "stacked"

function chooseBannerTier(width: number): BannerTier {
  if (width >= STANDARD_MIN_COLS) return "standard"
  if (width >= SMALL_MIN_COLS) return "small"
  return "stacked"
}

/**
 * Render a multi-line figlet block as one `<Text>` per row. Each row is its
 * own `<Text wrap={false}>` so a narrow container can't wrap the ASCII art
 * mid-glyph (the tier picker should already have chosen a smaller block, but
 * `wrap={false}` is belt-and-suspenders against alignment damage).
 */
function FigletBlock({ rows, color }: { rows: ReadonlyArray<string>; color: string }): React.ReactElement {
  return (
    <Box flexDirection="column" alignItems="center">
      {rows.map((row, i) => (
        <Text key={i} bold color={color} wrap={false}>
          {row}
        </Text>
      ))}
    </Box>
  )
}

/**
 * Silver Code banner — ◈ accent + figlet block letters + agent label.
 *
 * Two-color split: SILVER → `$primary` (cool brand mark), CODE → `$accent`
 * (warm contrast). Both are silvery semantic tokens that resolve sensibly
 * across 84+ themes. Tier-pick based on `availableWidth` so narrow panes
 * degrade gracefully:
 *
 *   width >= 36 → standard figlet (33-col blocks × 5 rows)
 *   width >= 28 → small figlet (26-col blocks × 4 rows)
 *   otherwise   → simple stacked text "SILVER" / "CODE"
 *
 * Bead: km-cr94.
 */
function SilverCodeBanner({
  agentLabel,
  availableWidth,
}: {
  agentLabel?: string
  availableWidth: number
}): React.ReactElement {
  const tier = chooseBannerTier(availableWidth)

  let block: React.ReactElement
  if (tier === "standard") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_STANDARD} color="$primary" />
        <FigletBlock rows={CODE_STANDARD} color="$accent" />
      </Box>
    )
  } else if (tier === "small") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_SMALL} color="$primary" />
        <FigletBlock rows={CODE_SMALL} color="$accent" />
      </Box>
    )
  } else {
    block = (
      <Box flexDirection="column" alignItems="center">
        <Text bold color="$primary">
          SILVER
        </Text>
        <Text bold color="$accent">
          CODE
        </Text>
      </Box>
    )
  }

  return (
    <Box flexDirection="column" alignItems="center" gap={1}>
      <Text bold color="$accent">
        ◈
      </Text>
      {block}
      {agentLabel ? <Small color="$muted">{agentLabel}</Small> : null}
    </Box>
  )
}

/**
 * Width-aware wrapper. `useBoxRect` reads the host node's measured width and
 * triggers a re-render when it changes. On the first paint width is 0 — we
 * default to a generous size so the banner doesn't flash through the
 * stacked fallback while layout settles.
 */
function MeasuredBanner({ agentLabel }: { agentLabel?: string }): React.ReactElement {
  const { width } = useBoxRect()
  const effectiveWidth = width > 0 ? width : 80
  return (
    <Box flexDirection="column" alignItems="center">
      <SilverCodeBanner agentLabel={agentLabel} availableWidth={effectiveWidth} />
    </Box>
  )
}

/**
 * Centered command box (silvery TextInput in a rounded-border frame). Width
 * is capped at 70 cols so it doesn't span the full pane on wide terminals,
 * and shrinks on narrow ones via flex.
 */
function CommandBox({
  draft,
  setDraft,
  onSubmit,
  placeholder,
}: {
  draft: string
  setDraft: (v: string) => void
  onSubmit: (v: string) => void
  placeholder: string
}): React.ReactElement {
  return (
    <Box flexDirection="row" justifyContent="center">
      <Box flexShrink={1} maxWidth={70} minWidth={0} flexBasis={70}>
        <TextInput
          value={draft}
          onChange={setDraft}
          onSubmit={onSubmit}
          placeholder={placeholder}
          // `isActive=false` so this input is a visual placeholder only.
          // The real keystroke surface for first-message entry remains the
          // App-level SessionPromptComposer — without this guard, two
          // active TextInputs would fight for keystrokes (the Welcome box
          // would intercept "foo &" before the composer's strip-&-trailing
          // path could run, breaking background-amp-suffix.test.tsx and
          // friends). Bead: km-cr94.
          isActive={false}
          prompt="> "
          promptColor="$accent"
          borderStyle="round"
          borderColor="$border-default"
          focusBorderColor="$border-focus"
        />
      </Box>
    </Box>
  )
}

/**
 * Empty-state card shown when a session has no messages yet.
 *
 * Layout (banner + agent label + middle slot + help surface), with the
 * middle slot switching between two variants based on session status:
 *   - status === "spawning": agent subprocess is still starting. There's
 *     nowhere to send a prompt yet, so the middle slot shows a muted
 *     "○ Spawning <agent> session <id>…" line instead of a command box.
 *     Once status flips to idle the command box takes its place.
 *   - otherwise (idle): centered TextInput command box. Enter calls
 *     `controller.send` which writes the user-message to the store AND
 *     ships it to claude — the existing first-turn primitive.
 *
 * Help surface (COMMANDS + KEYBINDINGS) renders below the middle slot in
 * both states so the user always has the slash-command reference at hand.
 *
 * Bead: km-cr94.
 */
export function Welcome(props: {
  handle: SessionHandle
  /** Canonical agent id — drives the `<agent label>` muted line below the banner. */
  agent?: string
  /** Session status from the store — drives the middle-slot variant. */
  status?: string
  /**
   * Controller — when provided in the idle state, the command box is wired
   * to `controller.send`. Without it (component-level fixture tests) the
   * input runs as a local-only buffer; the visual is identical.
   */
  controller?: Controller
}): React.ReactElement {
  const agentLabel = props.agent ? AGENT_LABELS[props.agent] : undefined
  const isSpawning = props.status === "spawning"
  const [draft, setDraft] = useState("")

  function onSubmit(value: string): void {
    const text = value.trim()
    if (text.length === 0) return
    // Idle path: `controller.send` writes the user-message to the store
    // AND ships it to claude in one shot (same primitive tryFlush uses on
    // turn-end auto-flush). When messages.length flips from 0 → 1 the
    // SessionCard switches from Welcome to SessionUpdateList automatically.
    props.controller?.send(props.handle.id, text)
    setDraft("")
  }

  // Truncate long session ids (UUIDs) so they fit the muted spawning line.
  const shortSessionId = (() => {
    const id = props.handle.session?.sessionId ?? props.handle.id
    if (typeof id !== "string") return ""
    if (id.length <= 24) return id
    return id.slice(0, 8) + "…"
  })()

  return (
    <Box flexDirection="column" flexGrow={1} gap={2} paddingY={1}>
      <Box flexDirection="column" alignItems="center">
        <MeasuredBanner agentLabel={agentLabel} />
      </Box>

      {/* Middle slot — command box (idle) or spawning indicator (spawning). */}
      {isSpawning ? (
        <Box flexDirection="row" justifyContent="center">
          <Muted>
            ○ Spawning {agentLabel ?? "session"}
            {shortSessionId ? ` ${shortSessionId}` : ""}…
          </Muted>
        </Box>
      ) : (
        <CommandBox draft={draft} setDraft={setDraft} onSubmit={onSubmit} placeholder="Type a message to start…" />
      )}

      <Box flexDirection="column">
        <Small color="$muted">COMMANDS</Small>
        <IntroRow name="/panel" desc="toggle the todos + agents side panel" />
        <IntroRow name="/history" desc="replay + search past sessions" />
        <IntroRow name="/mode [name]" desc="cycle plan / accept-edits / auto / bypass" />
        <IntroRow name="/handoff <prompt>" desc="move task + context to another session" />
        <IntroRow name="/fork" desc="spawn a seeded sibling session" />
        <IntroRow name="/spawn [name]" desc="open another session in the grid" />
      </Box>

      <Box flexDirection="column">
        <Small color="$muted">KEYBINDINGS</Small>
        <IntroRow name="ctrl-o" desc="toggle the side panel (todos + agents)" />
        <IntroRow name="ctrl-r" desc="history view" />
        <IntroRow name="ctrl-n" desc="next session (multi-session)" />
        <IntroRow name="ctrl-g v / s / x / z" desc="pane chord: vsplit / hsplit / close / zoom" />
        <IntroRow name="ctrl-g h/j/k/l" desc="swap focused pane with neighbor" />
        <IntroRow name="esc" desc="dismiss open overlays" />
        <IntroRow name="ctrl-c / ctrl-d ctrl-d" desc="exit silvercode" />
      </Box>
    </Box>
  )
}

function IntroRow({ name, desc }: { name: string; desc: string }): React.ReactElement {
  return (
    <Box flexDirection="row" gap={2} paddingLeft={2}>
      <Box flexBasis={24}>
        <Text color="$accent">{name}</Text>
      </Box>
      <Box flexGrow={1}>
        <Muted>{desc}</Muted>
      </Box>
    </Box>
  )
}
