import React from "react"
import { resolve as resolvePath } from "node:path"
import { existsSync, readFileSync } from "node:fs"
import { Box, Image, Muted, Small, Text, isKittyGraphicsSupported, useBoxRect, useTerm } from "silvery"
import { createLogger } from "loggily"
import type { SessionHandle } from "../controller.ts"
import { prefixSid } from "../sid-prefix.ts"
import { Chat } from "./Chat.tsx"

const welcomeLog = createLogger("silvercode:welcome")

/**
 * Per-agent display label. Mirrors the `AGENT_DISPLAY` map in `SidePanel.tsx`
 * so the welcome screen and the side-panel branding row stay in sync. Unknown
 * agent id → bare "Silver Code". Bead: km-silvercode.welcome-claude-hardcoded.
 */
const AGENT_LABELS: Readonly<Record<string, string>> = {
  claude: "Claude Code",
  "claude-code": "Claude Code",
  "claude-code-spawn": "Claude Code",
  "claude-code-sdk": "Claude Code",
  codex: "Codex",
  "codex-spawn": "Codex",
  gemini: "Gemini",
  "github-copilot-cli": "GitHub Copilot",
}

/*
 * SILVER / CODE figlet block letters (pre-generated, NOT runtime-rendered).
 *
 * Generated with `figlet` so the per-row character alignment is correct
 * (LLMs reliably misalign hand-rolled multi-line ASCII art — see memory:
 * `feedback-no-box-diagrams`). Pasted as string-literal constants so the
 * app has no runtime dep on figlet and the lines are immutable.
 *
 * To regenerate (output is deterministic for the given font + word):
 *   figlet -f Big      "SILVER"
 *   figlet -f Big      "CODE"
 *   figlet -f standard "SILVER"
 *   figlet -f standard "CODE"
 *   figlet -f small    "SILVER"
 *   figlet -f small    "CODE"
 *
 * Width / height measurements (load-bearing for the tier picker):
 *   Big      SILVER: 40 cols × 6 rows
 *   Big      CODE:   28 cols × 6 rows
 *   standard SILVER: 33 cols × 5 rows
 *   standard CODE:   24 cols × 5 rows
 *   small    SILVER: 26 cols × 4 rows
 *   small    CODE:   20 cols × 4 rows
 *
 * Bead: km-cr94.
 */

/*
 * Shaded tier — POSITIVE-SPACE, per-row gradient.
 *
 * The letters themselves are filled with shade chars (the gradient is in
 * the text, not the background). 7 rows per wordmark, each row uses a
 * single shade char in monotonic ░ ░ ▒ ▒ ▓ ▓ █ progression — so the
 * letter strokes fade from soft highlight at top to solid block at
 * bottom (classic old-Apple chrome). SILVER and CODE are stacked with a
 * blank row between them.
 *
 * Width: 52 cols (SILVER), 38 cols (CODE).
 * Height: 7 rows each text block + 1 blank separator = 15 rows total.
 *
 * Stored in apps/silvercode/silver-code.txt so the generated wordmark is
 * inspectable as an asset, like silver-code.png.
 *
 * Regenerate the positive-space art:
 *   figlet -f banner3 -w 200 SILVER | awk '
 *     NR==1||NR==2{gsub(/#/,"░");print}
 *     NR==3||NR==4{gsub(/#/,"▒");print}
 *     NR==5||NR==6{gsub(/#/,"▓");print}
 *     NR==7        {gsub(/#/,"█");print}'
 */
const SILVER_CODE_TEXT_PATH: string = (() => {
  const dir = import.meta.dirname ?? __dirname
  if (!dir) throw new Error("silvercode: unable to resolve module dir for silver-code.txt lookup")
  return resolvePath(dir, "..", "..", "silver-code.txt")
})()

function readTextLogoBlocks(path: string): readonly [ReadonlyArray<string>, ReadonlyArray<string>] {
  const blocks = readFileSync(path, "utf8")
    .trimEnd()
    .split(/\n\n/)
    .map((block) => block.split("\n"))
  if (blocks.length !== 2 || !blocks[0] || !blocks[1]) {
    throw new Error(`silvercode: silver-code.txt must contain SILVER and CODE blocks separated by one blank line`)
  }
  return [blocks[0], blocks[1]]
}

const [SILVER_SHADED_WIDE, CODE_SHADED_WIDE] = readTextLogoBlocks(SILVER_CODE_TEXT_PATH)

// generated by: figlet -f Big "SILVER"
const SILVER_BIG: ReadonlyArray<string> = [
  "  _____ _____ _ __      ________ _____  ",
  " / ____|_   _| |\\ \\    / /  ____|  __ \\ ",
  "| (___   | | | | \\ \\  / /| |__  | |__) |",
  " \\___ \\  | | | |  \\ \\/ / |  __| |  _  / ",
  " ____) |_| |_| |___\\  /  | |____| | \\ \\ ",
  "|_____/|_____|______\\/   |______|_|  \\_\\",
]

// generated by: figlet -f Big "CODE"
const CODE_BIG: ReadonlyArray<string> = [
  "  _____ ____  _____  ______ ",
  " / ____/ __ \\|  __ \\|  ____|",
  "| |   | |  | | |  | | |__   ",
  "| |   | |  | | |  | |  __|  ",
  "| |___| |__| | |__| | |____ ",
  " \\_____\\____/|_____/|______|",
]

// generated by: figlet -f standard "SILVER"
const SILVER_STANDARD: ReadonlyArray<string> = [
  " ____ ___ _ __     _______ ____  ",
  "/ ___|_ _| |\\ \\   / / ____|  _ \\ ",
  "\\___ \\| || | \\ \\ / /|  _| | |_) |",
  " ___) | || |__\\ V / | |___|  _ < ",
  "|____/___|_____\\_/  |_____|_| \\_\\",
]

// generated by: figlet -f standard "CODE"
const CODE_STANDARD: ReadonlyArray<string> = [
  "  ____ ___  ____  _____ ",
  " / ___/ _ \\|  _ \\| ____|",
  "| |  | | | | | | |  _|  ",
  "| |__| |_| | |_| | |___ ",
  " \\____\\___/|____/|_____|",
]

// generated by: figlet -f small "SILVER"
const SILVER_SMALL: ReadonlyArray<string> = [
  " ___ ___ _ __   _____ ___ ",
  "/ __|_ _| |\\ \\ / / __| _ \\",
  "\\__ \\| || |_\\ V /| _||   /",
  "|___/___|____\\_/ |___|_|_\\",
]

// generated by: figlet -f small "CODE"
const CODE_SMALL: ReadonlyArray<string> = [
  "  ___ ___  ___  ___ ",
  " / __/ _ \\|   \\| __|",
  "| (_| (_) | |) | _| ",
  " \\___\\___/|___/|___|",
]

/**
 * Resolved at module-load: absolute path to silver-code.png. The PNG
 * ships next to apps/silvercode/package.json, so from this file
 * (apps/silvercode/src/components/Welcome.tsx) it lives two dirs up.
 *
 * If the file is missing, we throw immediately so the failure is loud
 * (the alternative — silently falling back to text — masked the real
 * "I don't see the logo" symptom).
 */
const SILVER_CODE_PNG_PATH: string = (() => {
  const dir = import.meta.dirname ?? __dirname
  if (!dir) throw new Error("silvercode: unable to resolve module dir for silver-code.png lookup")
  const candidate = resolvePath(dir, "..", "..", "silver-code.png")
  if (!existsSync(candidate)) {
    throw new Error(`silvercode: silver-code.png not found at ${candidate}`)
  }
  return candidate
})()

/**
 * PNG dimensions read from the file header. We use the actual image's
 * aspect ratio rather than hardcoding any 3:2 / 3:1 / etc. constant —
 * if the asset gets re-cropped (which it has been) the displayed banner
 * automatically tracks the new aspect.
 *
 * PNG header layout: bytes 0-7 = magic, byte 8-11 = IHDR chunk length,
 * 12-15 = "IHDR", 16-19 = width (big-endian u32), 20-23 = height.
 */
const SILVER_CODE_PNG_DIMENSIONS: { readonly width: number; readonly height: number } = (() => {
  const head = readFileSync(SILVER_CODE_PNG_PATH).subarray(0, 24)
  const sig = head.subarray(0, 8).toString("hex")
  if (sig !== "89504e470d0a1a0a") {
    throw new Error(`silvercode: silver-code.png is not a valid PNG (sig=${sig})`)
  }
  const width = head.readUInt32BE(16)
  const height = head.readUInt32BE(20)
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    throw new Error(`silvercode: silver-code.png has invalid IHDR dimensions ${width}x${height}`)
  }
  return { width, height }
})()

/**
 * Min container width for each tier (cols). The ladder steps:
 *   ≥ 56 + Kitty graphics → Image (silver-code.png via Kitty/Sixel) — wide-terminal default
 *   ≥ 56 → Shaded (52 cols + breathing room) — text-only fallback
 *   ≥ 44 → Big (~40 cols)
 *   ≥ 36 → standard (33 cols)
 *   ≥ 28 → small (26 cols)
 *    < 28 → stacked-text fallback
 */
const SHADED_MIN_COLS = 56
const BIG_MIN_COLS = 44
const STANDARD_MIN_COLS = 36
const SMALL_MIN_COLS = 28
const IMAGE_MAX_COLS = 60
const IMAGE_MIN_COLS = 24

type BannerTier = "image" | "shaded" | "big" | "standard" | "small" | "stacked"

/**
 * Detect Kitty graphics protocol support once at module load. Test
 * envs (`NODE_ENV=test`, vitest) skip the image tier because termless
 * / createRenderer can't paint Kitty escapes — letting tests fall
 * through to the shaded text tier keeps assertion signatures stable.
 *
 * Detection errors are NOT swallowed — if `isKittyGraphicsSupported()`
 * throws, the exception propagates so the failure is visible.
 */
const KITTY_SUPPORTED: boolean = (() => {
  if (process.env.NODE_ENV === "test" || process.env.VITEST) return false
  return isKittyGraphicsSupported()
})()

function chooseBannerTier(width: number): BannerTier {
  // Image tier requires Kitty graphics support and enough room. Falls
  // through to the shaded text tier when Kitty isn't available; the
  // PNG path is mandatory at module load (throws if missing) so it's
  // not part of the runtime gate.
  if (width >= SHADED_MIN_COLS && KITTY_SUPPORTED) return "image"
  if (width >= SHADED_MIN_COLS) return "shaded"
  if (width >= BIG_MIN_COLS) return "big"
  if (width >= STANDARD_MIN_COLS) return "standard"
  if (width >= SMALL_MIN_COLS) return "small"
  return "stacked"
}

function imageCellSize(availableWidth: number): { readonly width: number; readonly height: number } {
  // Kitty graphics are placed into terminal cells. Terminal cells are roughly
  // twice as tall as wide, so the displayed cell aspect is the PNG aspect
  // divided by that cell-shape factor.
  const CELL_HEIGHT_TO_WIDTH = 2
  const { width: pngW, height: pngH } = SILVER_CODE_PNG_DIMENSIONS
  const width = Math.min(IMAGE_MAX_COLS, Math.max(IMAGE_MIN_COLS, availableWidth - 4))
  const height = Math.max(5, Math.round((width * pngH) / (pngW * CELL_HEIGHT_TO_WIDTH)))
  return { width, height }
}

/**
 * Render a multi-line figlet block as one `<Text>` per row. Each row is its
 * own `<Text wrap={false}>` so a narrow container can't wrap the ASCII art
 * mid-glyph (the tier picker should already have chosen a smaller block, but
 * `wrap={false}` is belt-and-suspenders against alignment damage).
 */
function FigletBlock({ rows, color }: { rows: ReadonlyArray<string>; color: string }): React.ReactElement {
  const width = Math.max(0, ...rows.map((row) => row.length))
  return (
    <Box flexDirection="column" alignItems="flex-start" width={width}>
      {rows.map((row, i) => (
        <Text key={i} bold color={color} wrap={false}>
          {row.replace(/ /g, "\u00a0")}
        </Text>
      ))}
    </Box>
  )
}

/**
 * Silver Code banner — block letters + agent label.
 *
 * Two-color split: SILVER → `$primary` (cool brand mark), CODE → `$accent`
 * (warm contrast). Both are silvery semantic tokens that resolve sensibly
 * across 84+ themes. The Big primary tier is the wordmark — when the user
 * opens silvercode on a wide terminal the banner occupies roughly the
 * upper third of the screen (~9 rows × 2 + gap + agent label ≈ 20 lines),
 * big enough to read as a product mark, not a footnote.
 *
 * Tier-pick based on `availableWidth` so narrow panes degrade gracefully:
 *   width >= 56 → Shaded blocks (52-col, 7 rows, ░░▒▒▓▓█ gradient) ← primary
 *   width >= 44 → Big figlet (40-col blocks × 6 rows)
 *   width >= 36 → standard figlet (33-col blocks × 5 rows)
 *   width >= 28 → small figlet (26-col blocks × 4 rows)
 *   otherwise   → simple stacked text "SILVER" / "CODE"
 *
 * Bead: km-cr94.
 */
export function SilverCodeBanner({
  agentLabel,
  availableWidth,
}: {
  agentLabel?: string
  availableWidth: number
}): React.ReactElement {
  const tier = chooseBannerTier(availableWidth)
  React.useEffect(() => {
    welcomeLog.debug?.("bannerTier", { availableWidth, tier, kittySupported: KITTY_SUPPORTED })
  }, [availableWidth, tier])

  let block: React.ReactElement
  if (tier === "image") {
    const { width: imgW, height: imgH } = imageCellSize(availableWidth)
    block = (
      <Box flexDirection="column" alignItems="center" marginBottom={2}>
        <Image src={SILVER_CODE_PNG_PATH} width={imgW} height={imgH} fallback="SILVER CODE" />
      </Box>
    )
  } else if (tier === "shaded") {
    // Positive-space gradient — letters are filled with shade chars
    // (░ ░ ▒ ▒ ▓ ▓ █ across the 7 rows of each wordmark), so the text
    // itself fades top-light to bottom-dark. SILVER and CODE are
    // stacked with one blank row between them.
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_SHADED_WIDE} color="$primary" />
        <FigletBlock rows={CODE_SHADED_WIDE} color="$accent" />
      </Box>
    )
  } else if (tier === "big") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_BIG} color="$primary" />
        <FigletBlock rows={CODE_BIG} color="$accent" />
      </Box>
    )
  } else if (tier === "standard") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_STANDARD} color="$primary" />
        <FigletBlock rows={CODE_STANDARD} color="$accent" />
      </Box>
    )
  } else if (tier === "small") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_SMALL} color="$primary" />
        <FigletBlock rows={CODE_SMALL} color="$accent" />
      </Box>
    )
  } else {
    block = (
      <Box flexDirection="column" alignItems="center">
        <Text bold color="$primary">
          SILVER
        </Text>
        <Text bold color="$accent">
          CODE
        </Text>
      </Box>
    )
  }

  return (
    <Box flexDirection="column" alignItems="center" gap={1}>
      {block}
      {agentLabel ? <Small color="$muted">{agentLabel}</Small> : null}
    </Box>
  )
}

function FixedBitmapBanner(): React.ReactElement {
  const cols = useTerm((term) => term.size.cols())
  const availableWidth = Math.max(IMAGE_MIN_COLS + 4, Math.floor(cols * 0.45))
  const { width, height } = imageCellSize(availableWidth)
  React.useEffect(() => {
    welcomeLog.debug?.("bitmapBanner", { termCols: cols, availableWidth, imageWidth: width, imageHeight: height })
  }, [availableWidth, cols, height, width])
  return (
    <Box flexDirection="column" alignItems="center" marginBottom={2}>
      <Image src={SILVER_CODE_PNG_PATH} width={width} height={height} fallback="" />
    </Box>
  )
}

/**
 * Width-aware wrapper. Uses silvery's `<MeasuredBox>` primitive — defers
 * children until layout has measured the host's positive cell width, so
 * the banner doesn't flash at a fallback width on first paint and then
 * re-paint at the real width.
 *
 * `alignSelf="stretch"` makes this Box fill the parent's cross-axis so
 * the measurement reads the FULL pane width — needed by the shaded tier
 * for full-width row padding.
 */
export function MeasuredBanner({ agentLabel }: { agentLabel?: string }): React.ReactElement {
  const rect = useBoxRect()
  const termCols = useTerm((term) => term.size.cols())
  const availableWidth = rect.width > 0 ? rect.width : termCols
  React.useEffect(() => {
    welcomeLog.debug?.("bannerMeasure", {
      rectWidth: rect.width,
      rectHeight: rect.height,
      termCols,
      availableWidth,
      usedFallback: rect.width <= 0,
    })
  }, [availableWidth, rect.height, rect.width, termCols])
  return (
    <Box flexDirection="column" alignSelf="stretch" width="100%" alignItems="center">
      <SilverCodeBanner agentLabel={agentLabel} availableWidth={availableWidth} />
    </Box>
  )
}

export function StaticTextBanner({ agentLabel }: { agentLabel?: string }): React.ReactElement {
  return (
    <Box flexDirection="column" alignItems="center" gap={1}>
      <FigletBlock rows={SILVER_SHADED_WIDE} color="$primary" />
      <FigletBlock rows={CODE_SHADED_WIDE} color="$accent" />
      {agentLabel ? <Small color="$muted">{agentLabel}</Small> : null}
    </Box>
  )
}

/** Truncate UUID-style ids to a readable prefix for the loading line. */
export function shortenSessionId(id: string | undefined): string {
  if (!id) return ""
  if (id.length <= 24) return id
  return id.slice(0, 8) + "…"
}

export function formatLoadingSessionId(id: string | undefined, agent: string | undefined): string {
  if (!id) return ""
  return agent ? prefixSid(agent, id) : id
}

function formatAgentModelDetails({ agentLabel, model }: { agentLabel?: string; model?: string }): string {
  return [agentLabel, model].filter((part): part is string => Boolean(part && part.length > 0)).join(" · ")
}

const WELCOME_BANNER_FLEX = 58
const WELCOME_BODY_FLEX = 42

/**
 * Empty-state screen — banner + the App-level `SessionPromptComposer`,
 * both centered. The composer is THE SAME element rendered at the bottom
 * of the layout in chat state — App threads it down as `composerSlot`
 * so we keep one component and one set of state. Only its parent slot
 * differs (centered here vs bottom-anchored in chat state).
 *
 * Visually: banner + agent label, optionally a quiet two-line loading
 * state (resume), and the composer when supplied. Resume replay is a
 * loading state, so it suppresses the input surface until the transcript
 * has loaded enough to enter the normal chat layout.
 */
export function Welcome(props: {
  handle: SessionHandle
  /** Canonical agent id — drives the `<agent label>` muted line below the banner. */
  agent?: string
  /** Model label for the loading line. Falls back to handle metadata. */
  model?: string
  /**
   * The App-level `SessionPromptComposer` element, threaded through
   * PaneGrid → ChatPane so the composer here and the (suppressed)
   * bottom-anchored render reference the same controlled component +
   * App-owned state. Width-capped here for visual centering; placement
   * is the only difference from the chat-state render. When omitted
   * (component-level fixture tests), the centered slot is empty and
   * the test asserts banner-only chrome.
   */
  composerSlot?: React.ReactNode
  /** Force a text banner. Storybook uses this inside scroll containers so
   * Kitty bitmap placements don't re-anchor while the user scrolls. */
  bitmapBanner?: boolean
  /** App welcome fills and centers the pane; storybook renders it inline. */
  centerVertically?: boolean
}): React.ReactElement {
  const agentLabel = props.agent ? AGENT_LABELS[props.agent] : undefined
  const resumeId = formatLoadingSessionId(props.handle.resumeId, props.agent)
  const hasResumeId = typeof resumeId === "string" && resumeId.length > 0
  // Only suppress the composer during resume replay — the transcript is
  // loading and the user can't send a new turn yet. Do NOT suppress during
  // spawning: the session is initialising but the input is already live
  // (buffered prompts are replayed into the handle once it is ready), and
  // hiding then re-showing the composer causes a layout jump after 3-5s
  // plus resets the cursor position. Matches the PaneGrid pre-spawn screen
  // which shows the composer immediately without a spawning guard.
  const isLoading = hasResumeId
  const loadingSessionId = hasResumeId
    ? resumeId
    : props.handle.metadata?.sessionId || props.handle.id || props.handle.name
  const agentModelDetails = formatAgentModelDetails({
    model: props.model || props.handle.metadata?.model,
  })
  const centerVertically = props.centerVertically !== false
  const showComposer = Boolean(props.composerSlot && !isLoading)
  const banner =
    props.bitmapBanner === false ? <StaticTextBanner /> : KITTY_SUPPORTED ? <FixedBitmapBanner /> : <MeasuredBanner />
  const bannerKind = props.bitmapBanner === false ? "static-text" : KITTY_SUPPORTED ? "bitmap" : "measured-text"
  React.useEffect(() => {
    welcomeLog.debug?.("render", {
      agent: props.agent,
      agentLabel,
      bannerKind,
      centerVertically,
      hasResumeId,
      isLoading,
      showComposer,
      hasComposerSlot: Boolean(props.composerSlot),
      model: props.model,
    })
  }, [
    agentLabel,
    bannerKind,
    centerVertically,
    hasResumeId,
    isLoading,
    props.agent,
    props.composerSlot,
    props.model,
    showComposer,
  ])
  const lowerContent = (
    <Box flexDirection="column" alignItems="center" gap={1} width="100%" minWidth={0}>
      {agentLabel ? <Small color="$muted">{agentLabel}</Small> : null}
      {agentModelDetails.length > 0 ? <Muted>{agentModelDetails}</Muted> : null}
      {isLoading ? (
        <Box flexDirection="column" alignItems="center">
          <Muted>Loading session</Muted>
          {loadingSessionId.length > 0 ? <Muted>{loadingSessionId}</Muted> : null}
        </Box>
      ) : null}
      {showComposer ? (
        <Chat.Composer>
          <Box alignSelf="center" width="70%" minWidth={0}>
            {props.composerSlot}
          </Box>
        </Chat.Composer>
      ) : null}
    </Box>
  )

  return (
    // Reserve the upper part of the welcome screen for the logo and align
    // the artwork to the bottom of that slot. The model/loading/composer
    // rows then flow underneath in normal flex order, so late image/terminal
    // measurement cannot push them down.
    <Box
      flexDirection="column"
      flexGrow={centerVertically ? 1 : 0}
      alignItems="center"
      justifyContent="flex-start"
      gap={1}
      minHeight={0}
      width="100%"
    >
      <Box
        flexDirection="column"
        alignSelf="stretch"
        alignItems="center"
        justifyContent={centerVertically ? "flex-end" : "flex-start"}
        flexGrow={centerVertically ? WELCOME_BANNER_FLEX : 0}
        flexBasis={centerVertically ? 0 : "auto"}
        flexShrink={centerVertically ? 1 : 0}
        minHeight={0}
        overflow="hidden"
      >
        {banner}
      </Box>
      <Box flexGrow={centerVertically ? WELCOME_BODY_FLEX : 0} flexBasis={0} minHeight={0} width="100%">
        {lowerContent}
      </Box>
    </Box>
  )
}
