import React, { useState } from "react"
import { Box, Muted, Small, Text, TextInput, useBoxRect } from "silvery"
import type { Controller, SessionHandle } from "../controller.ts"

/**
 * Per-agent display label. Mirrors the `AGENT_DISPLAY` map in `SidePanel.tsx`
 * so the welcome card and the side-panel branding row stay in sync. Unknown
 * agent id → bare "Silver Code". Bead: km-silvercode.welcome-claude-hardcoded.
 */
const AGENT_LABELS: Readonly<Record<string, string>> = {
  "claude-code": "Claude Code",
  "claude-code-spawn": "Claude Code",
  "claude-code-sdk": "Claude Code",
  codex: "Codex",
  "codex-spawn": "Codex",
  gemini: "Gemini",
  "github-copilot-cli": "GitHub Copilot",
}

/*
 * SILVER / CODE figlet block letters (pre-generated, NOT runtime-rendered).
 *
 * Generated with `figlet` so the per-row character alignment is correct
 * (LLMs reliably misalign hand-rolled multi-line ASCII art — see memory:
 * `feedback-no-box-diagrams`). Pasted as string-literal constants so the
 * app has no runtime dep on figlet and the lines are immutable.
 *
 * To regenerate (output is deterministic for the given font + word):
 *   figlet -f Big      "SILVER"
 *   figlet -f Big      "CODE"
 *   figlet -f standard "SILVER"
 *   figlet -f standard "CODE"
 *   figlet -f small    "SILVER"
 *   figlet -f small    "CODE"
 *
 * Width / height measurements (load-bearing for the tier picker):
 *   Big      SILVER: 40 cols × 6 rows
 *   Big      CODE:   28 cols × 6 rows
 *   standard SILVER: 33 cols × 5 rows
 *   standard CODE:   24 cols × 5 rows
 *   small    SILVER: 26 cols × 4 rows
 *   small    CODE:   20 cols × 4 rows
 *
 * Bead: km-cr94.
 */

// generated by: figlet -f Big "SILVER"
const SILVER_BIG: ReadonlyArray<string> = [
  "  _____ _____ _ __      ________ _____  ",
  " / ____|_   _| |\\ \\    / /  ____|  __ \\ ",
  "| (___   | | | | \\ \\  / /| |__  | |__) |",
  " \\___ \\  | | | |  \\ \\/ / |  __| |  _  / ",
  " ____) |_| |_| |___\\  /  | |____| | \\ \\ ",
  "|_____/|_____|______\\/   |______|_|  \\_\\",
]

// generated by: figlet -f Big "CODE"
const CODE_BIG: ReadonlyArray<string> = [
  "  _____ ____  _____  ______ ",
  " / ____/ __ \\|  __ \\|  ____|",
  "| |   | |  | | |  | | |__   ",
  "| |   | |  | | |  | |  __|  ",
  "| |___| |__| | |__| | |____ ",
  " \\_____\\____/|_____/|______|",
]

// generated by: figlet -f standard "SILVER"
const SILVER_STANDARD: ReadonlyArray<string> = [
  " ____ ___ _ __     _______ ____  ",
  "/ ___|_ _| |\\ \\   / / ____|  _ \\ ",
  "\\___ \\| || | \\ \\ / /|  _| | |_) |",
  " ___) | || |__\\ V / | |___|  _ < ",
  "|____/___|_____\\_/  |_____|_| \\_\\",
]

// generated by: figlet -f standard "CODE"
const CODE_STANDARD: ReadonlyArray<string> = [
  "  ____ ___  ____  _____ ",
  " / ___/ _ \\|  _ \\| ____|",
  "| |  | | | | | | |  _|  ",
  "| |__| |_| | |_| | |___ ",
  " \\____\\___/|____/|_____|",
]

// generated by: figlet -f small "SILVER"
const SILVER_SMALL: ReadonlyArray<string> = [
  " ___ ___ _ __   _____ ___ ",
  "/ __|_ _| |\\ \\ / / __| _ \\",
  "\\__ \\| || |_\\ V /| _||   /",
  "|___/___|____\\_/ |___|_|_\\",
]

// generated by: figlet -f small "CODE"
const CODE_SMALL: ReadonlyArray<string> = [
  "  ___ ___  ___  ___ ",
  " / __/ _ \\|   \\| __|",
  "| (_| (_) | |) | _| ",
  " \\___\\___/|___/|___|",
]

/**
 * Min container width for each tier (cols). The ladder steps:
 *   ≥ 44 → Big (primary, ~40 cols + breathing room) — wide-terminal default
 *   ≥ 36 → standard (33 cols)
 *   ≥ 28 → small (26 cols)
 *    < 28 → stacked-text fallback
 */
const BIG_MIN_COLS = 44
const STANDARD_MIN_COLS = 36
const SMALL_MIN_COLS = 28

type BannerTier = "big" | "standard" | "small" | "stacked"

function chooseBannerTier(width: number): BannerTier {
  if (width >= BIG_MIN_COLS) return "big"
  if (width >= STANDARD_MIN_COLS) return "standard"
  if (width >= SMALL_MIN_COLS) return "small"
  return "stacked"
}

/**
 * Render a multi-line figlet block as one `<Text>` per row. Each row is its
 * own `<Text wrap={false}>` so a narrow container can't wrap the ASCII art
 * mid-glyph (the tier picker should already have chosen a smaller block, but
 * `wrap={false}` is belt-and-suspenders against alignment damage).
 */
function FigletBlock({ rows, color }: { rows: ReadonlyArray<string>; color: string }): React.ReactElement {
  return (
    <Box flexDirection="column" alignItems="center">
      {rows.map((row, i) => (
        <Text key={i} bold color={color} wrap={false}>
          {row}
        </Text>
      ))}
    </Box>
  )
}

/**
 * Silver Code banner — ◈ accent + figlet block letters + agent label.
 *
 * Two-color split: SILVER → `$primary` (cool brand mark), CODE → `$accent`
 * (warm contrast). Both are silvery semantic tokens that resolve sensibly
 * across 84+ themes. The Big primary tier is the wordmark — when the user
 * opens silvercode on a wide terminal the banner occupies roughly the
 * upper third of the screen (6 rows × 2 + gaps + ◈ + agent label ≈ 16-18
 * lines), big enough to read as a product mark, not a footnote.
 *
 * Tier-pick based on `availableWidth` so narrow panes degrade gracefully:
 *   width >= 44 → Big figlet (40-col blocks × 6 rows)        ← primary
 *   width >= 36 → standard figlet (33-col blocks × 5 rows)
 *   width >= 28 → small figlet (26-col blocks × 4 rows)
 *   otherwise   → simple stacked text "SILVER" / "CODE"
 *
 * Bead: km-cr94.
 */
function SilverCodeBanner({
  agentLabel,
  availableWidth,
}: {
  agentLabel?: string
  availableWidth: number
}): React.ReactElement {
  const tier = chooseBannerTier(availableWidth)

  let block: React.ReactElement
  if (tier === "big") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_BIG} color="$primary" />
        <FigletBlock rows={CODE_BIG} color="$accent" />
      </Box>
    )
  } else if (tier === "standard") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_STANDARD} color="$primary" />
        <FigletBlock rows={CODE_STANDARD} color="$accent" />
      </Box>
    )
  } else if (tier === "small") {
    block = (
      <Box flexDirection="column" alignItems="center" gap={1}>
        <FigletBlock rows={SILVER_SMALL} color="$primary" />
        <FigletBlock rows={CODE_SMALL} color="$accent" />
      </Box>
    )
  } else {
    block = (
      <Box flexDirection="column" alignItems="center">
        <Text bold color="$primary">
          SILVER
        </Text>
        <Text bold color="$accent">
          CODE
        </Text>
      </Box>
    )
  }

  return (
    <Box flexDirection="column" alignItems="center" gap={1}>
      <Text bold color="$accent">
        ◈
      </Text>
      {block}
      {agentLabel ? <Small color="$muted">{agentLabel}</Small> : null}
    </Box>
  )
}

/**
 * Width-aware wrapper. `useBoxRect` reads the host node's measured width and
 * triggers a re-render when it changes. On the first paint width is 0 — we
 * default to a generous size so the banner doesn't flash through the
 * stacked fallback while layout settles.
 */
function MeasuredBanner({ agentLabel }: { agentLabel?: string }): React.ReactElement {
  const { width } = useBoxRect()
  const effectiveWidth = width > 0 ? width : 80
  return (
    <Box flexDirection="column" alignItems="center">
      <SilverCodeBanner agentLabel={agentLabel} availableWidth={effectiveWidth} />
    </Box>
  )
}

/**
 * Centered command box (silvery TextInput in a rounded-border frame). Width
 * is capped at 70 cols so it doesn't span the full pane on wide terminals,
 * and shrinks on narrow ones via flex.
 */
function CommandBox({
  draft,
  setDraft,
  onSubmit,
  placeholder,
}: {
  draft: string
  setDraft: (v: string) => void
  onSubmit: (v: string) => void
  placeholder: string
}): React.ReactElement {
  return (
    <Box flexDirection="row" justifyContent="center">
      <Box flexShrink={1} maxWidth={70} minWidth={0} flexBasis={70}>
        <TextInput
          value={draft}
          onChange={setDraft}
          onSubmit={onSubmit}
          placeholder={placeholder}
          // `isActive=false` so this input is a visual placeholder only.
          // The real keystroke surface for first-message entry remains the
          // App-level SessionPromptComposer — without this guard, two
          // active TextInputs would fight for keystrokes (the Welcome box
          // would intercept "foo &" before the composer's strip-&-trailing
          // path could run, breaking background-amp-suffix.test.tsx and
          // friends). Bead: km-cr94.
          isActive={false}
          prompt="> "
          promptColor="$accent"
          borderStyle="round"
          borderColor="$border-default"
          focusBorderColor="$border-focus"
        />
      </Box>
    </Box>
  )
}

/** Truncate UUID-style ids to a readable prefix for the loading line. */
function shortenSessionId(id: string | undefined): string {
  if (!id) return ""
  if (id.length <= 24) return id
  return id.slice(0, 8) + "…"
}

/**
 * Empty-state screen shown when `messages.length === 0`. Centered both
 * vertically and horizontally — the entire pane is the brand mark and one
 * affordance below it. Two variants, picked by `handle.resumeId`:
 *
 *   Fresh session (no `--resume`): banner + centered command box. The
 *     command box renders in both `spawning` and `idle` status — status
 *     just affects whether claude is reachable yet, not the visual. The
 *     real keystroke surface is the App-level SessionPromptComposer; this
 *     command box is a visual placeholder (`isActive=false`) so two
 *     TextInputs don't fight for keystrokes.
 *
 *   Loading session (`--resume <id>`): banner + muted "Loading session
 *     <id>…" line. NO command box — the user is waiting for the JSONL
 *     transcript replay to complete; once it does, `messages.length`
 *     becomes > 0 and the SessionCard switches to the chat view.
 *
 * Help surface (COMMANDS / KEYBINDINGS) is OFF this screen by design —
 * banner + box-or-loading is the entire screen. The chat view's composer
 * surfaces command hints on demand. Bead: km-cr94.
 */
export function Welcome(props: {
  handle: SessionHandle
  /** Canonical agent id — drives the `<agent label>` muted line below the banner. */
  agent?: string
  /** Session status from the store. Currently informational only — the
   *  fresh/loading split is driven by `handle.resumeId`, not status. */
  status?: string
  /**
   * Controller — when provided in the fresh-session path, the command box
   * is wired to `controller.send`. Without it (component-level fixture
   * tests) the input runs as a local-only buffer; the visual is identical.
   */
  controller?: Controller
}): React.ReactElement {
  const agentLabel = props.agent ? AGENT_LABELS[props.agent] : undefined
  const resumeId = props.handle.resumeId
  const isLoading = typeof resumeId === "string" && resumeId.length > 0
  const [draft, setDraft] = useState("")

  function onSubmit(value: string): void {
    const text = value.trim()
    if (text.length === 0) return
    // `controller.send` writes the user-message to the store AND ships it
    // to claude — or queues it if status !== "idle" yet. Either way, when
    // messages.length flips 0 → 1 the SessionCard switches to chat view.
    props.controller?.send(props.handle.id, text)
    setDraft("")
  }

  return (
    // Center the brand mark + affordance on both axes. `flexGrow={1}` claims
    // the full pane height; `justifyContent="center"` + `alignItems="center"`
    // pin contents to the visual center. `gap={2}` sets breathing room
    // between the banner and whatever sits below it.
    <Box flexDirection="column" flexGrow={1} alignItems="center" justifyContent="center" gap={2} paddingX={2}>
      <MeasuredBanner agentLabel={agentLabel} />

      {isLoading ? (
        // Resume path — quiet "Loading session <id>…" line, no input.
        <Muted>Loading session {shortenSessionId(resumeId)}…</Muted>
      ) : (
        // Fresh path — centered command box.
        <CommandBox draft={draft} setDraft={setDraft} onSubmit={onSubmit} placeholder="Type a message to start…" />
      )}
    </Box>
  )
}
