/**
 * `km agent spawn @agent/<N>` — slot orchestrator (Phase 3.3 of @km/agent/sigil-boards).
 *
 * Three-step launcher:
 *   1. Claim the slot (CAS via repo.tryClaim once Phase 1.3 lands; today via
 *      planClaim+applyLifecyclePlan as a stop-gap).
 *   2. Compose a session brief — persona body + env block — to a temp file.
 *   3. Launch the configured agent (default `silvercode`) wired to the brief
 *      with stdio: "inherit". Releases the claim on exit / SIGINT / SIGTERM.
 *
 * Agent-agnostic by design — silvercode is the canonical km-aware harness;
 * other agents integrate by accepting `--system-prompt-file` (or equivalent).
 *
 * Tribe broadcasts at every transition (claim, spawn, release) via
 * `bun vendor/bearly/tools/tribe-cli.ts send`. Best-effort — daemon being down
 * never blocks the spawn.
 *
 * --dry-run: prints the composed brief + planned exec command and exits.
 * Does NOT claim, does NOT spawn.
 */

import { spawn } from "node:child_process"
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, isAbsolute } from "node:path"

import { resolvePathArg } from "@km/fs-mount"
import type { KNode } from "@km/core"
import type { Repo } from "@km/storage"
import { createTerm } from "@silvery/ag-react"

import { loadRepo } from "../load-repo.ts"
import { getRootPath } from "../program.ts"
import { resolveAssignee } from "../utils/assignee.ts"
import { applyLifecyclePlan, ClaimContentionError, planClaim, planRelease } from "./tasks/lifecycle.ts"

const term = createTerm(process)

/** Slot id form `@agent/<N>` where N is 0..9. */
const SLOT_PATTERN = /^@agent\/[0-9]+$/

export function isAgentSlotRef(name: string): boolean {
  return SLOT_PATTERN.test(name)
}

export type AgentRuntime = "silvercode" | "claude" | "pi" | "headless-acp"

export interface SpawnOptions {
  /** Default `silvercode`. */
  agent?: AgentRuntime
  /** When true, print the brief + planned exec and exit without claiming. */
  dryRun?: boolean
}

/** Default agent lease (seconds). Mirrors the 20-min agent lease the bead spec assumes. */
const DEFAULT_LEASE_SECONDS = 20 * 60

/**
 * Resolve the slot node by its `@agent/N` ref.
 *
 * Tries `repo.resolveNode` first; falls back to `repo.resolveByName` so the
 * orchestrator works in test repos where the resolver chain may not yet
 * recognize the sigil-board form.
 */
function resolveSlotNode(repo: Repo, slotRef: string): KNode | null {
  const viaResolve = repo.resolveNode(slotRef)
  if (viaResolve) return viaResolve
  const viaName = repo.resolveByName(slotRef)
  return viaName ?? null
}

/**
 * Compose the session-brief markdown injected into the agent's system prompt.
 *
 * Layout:
 *   <persona>...slot body...</persona>
 *   <env>TRIBE_NAME=...; KM_AGENT_SLOT=...; KM_VAULT_ROOT=...</env>
 */
export function composeSessionBrief(input: {
  slotRef: string
  vaultRoot: string
  personaBody: string
  timestamp: string
}): string {
  const { slotRef, vaultRoot, personaBody, timestamp } = input
  return [
    `<!-- system prompt for ${slotRef} — generated by \`km agent spawn\` -->`,
    `<!-- timestamp: ${timestamp}, vault: ${vaultRoot}, slot: ${slotRef} -->`,
    "",
    "<persona>",
    personaBody.trim().length > 0 ? personaBody : `(empty persona — slot ${slotRef} has no body content)`,
    "</persona>",
    "",
    "<env>",
    `TRIBE_NAME=${slotRef}`,
    `KM_AGENT_SLOT=${slotRef}`,
    `KM_VAULT_ROOT=${vaultRoot}`,
    "</env>",
    "",
  ].join("\n")
}

/** Default actor identity used as the claim owner / tribe sender label. */
function defaultActor(): string {
  return process.env.TRIBE_NAME || `claude:agent-spawn-${process.pid}`
}

/**
 * Best-effort tribe broadcast.
 *
 * Spawns the bearly tribe-cli; if the daemon is down or the binary is
 * unreachable, swallow the error — coordination chatter must NEVER block
 * a spawn or a release.
 */
function tribeBroadcast(message: string): void {
  try {
    const cliPath = join(process.cwd(), "vendor", "bearly", "tools", "tribe-cli.ts")
    // Detached + unref so the child outlives us if needed (release path).
    const child = spawn("bun", [cliPath, "send", "*", message], {
      stdio: "ignore",
      detached: true,
    })
    child.unref()
  } catch {
    // intentionally swallow — tribe is best-effort
  }
}

/**
 * Race-safe claim path — uses the CAS-routed `planClaim` + `applyLifecyclePlan`.
 *
 * Phase 1.3 of @km/agent/sigil-boards landed atomic CAS via `repo.tryClaim`;
 * `planClaim` no longer rejects on owner-mismatch (which used to race), and
 * `applyLifecyclePlan` throws `ClaimContentionError` on lock-loss with the
 * holder + expiry attached. We pluck them out here for the orchestrator's
 * "already running as <holder>" message.
 */
function tryClaimSlot(
  repo: Repo,
  node: KNode,
  slotRef: string,
  actor: string,
): { ok: true; expiresAt: string } | { ok: false; holder: string; expiresAt: string | null } {
  const plan = planClaim(node, slotRef, actor)
  if (plan.errors.length > 0) {
    // Done/dropped/not-found — pre-flight rejections.
    return { ok: false, holder: "unknown", expiresAt: null }
  }
  try {
    applyLifecyclePlan(repo, node, plan)
  } catch (err) {
    if (err instanceof ClaimContentionError) {
      const holder = err.detail.currentOwner ?? "unknown"
      const expiresAt = err.detail.expiresAt ? new Date(err.detail.expiresAt).toISOString() : null
      return { ok: false, holder, expiresAt }
    }
    throw err
  }
  // Lease expiry is informational here; the real CAS path will return it.
  const expiresAt = new Date(Date.now() + DEFAULT_LEASE_SECONDS * 1000).toISOString()
  return { ok: true, expiresAt }
}

/**
 * Release the claim on the slot.
 *
 * Mirrors the planClaim stop-gap — uses planRelease + applyLifecyclePlan.
 * Best-effort: errors during shutdown should never crash the wrapper.
 */
function releaseSlot(repo: Repo, slotRef: string): void {
  try {
    const node = resolveSlotNode(repo, slotRef)
    if (!node) return
    const plan = planRelease(node, slotRef)
    if (plan.errors.length > 0) return
    applyLifecyclePlan(repo, node, plan)
  } catch {
    // never throw on release
  }
}

/**
 * Build the exec command for the chosen agent runtime.
 *
 * Contract: every supported agent accepts a system prompt file and a working
 * directory. Flag spelling differs per runtime; the orchestrator owns the
 * mapping so callers don't have to.
 */
export function buildExecCommand(input: { agent: AgentRuntime; briefPath: string; vaultRoot: string }): {
  cmd: string
  args: string[]
  note?: string
} {
  const { agent, briefPath, vaultRoot } = input
  switch (agent) {
    case "silvercode":
      return {
        cmd: "silvercode",
        args: ["--system-prompt-file", briefPath, "--working-dir", vaultRoot],
        note: "If silvercode lacks --system-prompt-file, add it for full Phase 3 integration.",
      }
    case "claude":
      // claude CLI accepts --append-system-prompt as a string and --cwd.
      return {
        cmd: "claude",
        args: ["--append-system-prompt", readFileSafe(briefPath), "--cwd", vaultRoot],
      }
    case "pi":
      return {
        cmd: "pi",
        args: ["--system-prompt-file", briefPath, "--cwd", vaultRoot],
        note: "TODO: pi runtime integration not yet wired (Phase 3 follow-up).",
      }
    case "headless-acp":
      return {
        cmd: "headless-acp",
        args: ["--system-prompt-file", briefPath, "--cwd", vaultRoot],
        note: "TODO: headless-acp runtime integration not yet wired (Phase 3 follow-up).",
      }
  }
}

/** Read a file synchronously, return empty string on failure (used for inline brief content). */
function readFileSafe(path: string): string {
  try {
    return readFileSync(path, "utf-8")
  } catch {
    return ""
  }
}

/**
 * Strip leading YAML frontmatter from a markdown source string.
 *
 * Slot files have shape:
 *   ---
 *   key: value
 *   ---
 *
 *   # [ ] @agent/N
 *
 *   ...persona body...
 *
 * The H1 inline goes onto `node.content`; the body paragraphs become child
 * nodes, so reading `node.content` alone misses the persona text. Reading
 * the source file and stripping frontmatter is the cheapest way to recover
 * the full body verbatim — exactly what the bead spec asks for ("the slot's
 * .md body becomes the session's persona context").
 */
function stripFrontmatter(source: string): string {
  if (!source.startsWith("---")) return source
  const closing = source.indexOf("\n---", 3)
  if (closing === -1) return source
  // skip past the closing fence and any trailing newline
  const after = source.slice(closing + 4)
  return after.startsWith("\n") ? after.slice(1) : after
}

/**
 * Resolve the persona body text for the slot.
 *
 * Prefers reading the slot's .md file (so the H1 + body paragraphs come
 * through verbatim). Falls back to `node.content` when the file isn't
 * accessible — keeps the orchestrator usable in non-FS-backed test repos.
 */
function readPersonaBody(node: KNode, vaultRoot: string): string {
  if (node.fs_path) {
    const fullPath = isAbsolute(node.fs_path) ? node.fs_path : join(vaultRoot, node.fs_path)
    try {
      const raw = readFileSync(fullPath, "utf-8")
      return stripFrontmatter(raw).trim()
    } catch {
      // fall through
    }
  }
  return (node.content ?? "").trim()
}

/**
 * Top-level entry — `km agent spawn @agent/<N>`.
 */
export async function spawnAgentSlot(slotRef: string, opts: SpawnOptions = {}): Promise<void> {
  if (!isAgentSlotRef(slotRef)) {
    console.error(term.red(`Invalid slot ref: ${slotRef} (expected @agent/<N>)`))
    process.exit(1)
  }

  const agent: AgentRuntime = opts.agent ?? "silvercode"
  const pathResolved = resolvePathArg(process.cwd(), getRootPath())
  const vaultRoot = pathResolved.repoRoot
  using repo = await loadRepo(vaultRoot)

  const slotNode = resolveSlotNode(repo, slotRef)
  if (!slotNode) {
    console.error(term.red(`Slot not found: ${slotRef}`))
    console.error(
      term.dim(
        `  Hint: Phase 2 of @km/agent/sigil-boards scaffolds @agent/0..9.md at the vault root. Make sure that's run.`,
      ),
    )
    process.exit(1)
  }

  const personaBody = readPersonaBody(slotNode, vaultRoot)
  const timestamp = new Date().toISOString()
  const brief = composeSessionBrief({ slotRef, vaultRoot, personaBody, timestamp })

  // Dry-run: print the brief + planned exec, do NOT claim, do NOT spawn.
  if (opts.dryRun) {
    const planned = buildExecCommand({ agent, briefPath: "<temp-file>", vaultRoot })
    console.log(term.bold(`[dry-run] would spawn ${slotRef} (agent=${agent})`))
    console.log(term.dim("--- session brief ---"))
    console.log(brief)
    console.log(term.dim("--- planned exec ---"))
    console.log(`  ${planned.cmd} ${planned.args.map((a) => JSON.stringify(a)).join(" ")}`)
    if (planned.note) console.log(term.yellow(`  note: ${planned.note}`))
    return
  }

  // Step 1: claim the slot.
  const actor = defaultActor()
  const claimResult = tryClaimSlot(repo, slotNode, slotRef, actor)
  if (!claimResult.ok) {
    console.error(
      term.red(
        `claim failed — held by ${claimResult.holder}${claimResult.expiresAt ? ` until ${claimResult.expiresAt}` : ""}`,
      ),
    )
    process.exit(1)
  }
  console.log(term.green(`claimed ${slotRef} (lease=${DEFAULT_LEASE_SECONDS}s, expires=${claimResult.expiresAt})`))
  tribeBroadcast(`spawned ${slotRef} agent=${agent} pid=${process.pid}`)

  // Step 2: compose the session brief on disk.
  const tmpRoot = process.env.KM_TMP || tmpdir()
  const tmpDir = mkdtempSync(join(tmpRoot, "km-agent-spawn-"))
  const slotN = slotRef.split("/")[1] ?? "x"
  const briefPath = join(tmpDir, `system-prompt-${slotN}-${Date.now()}.md`)
  writeFileSync(briefPath, brief, "utf-8")

  // Step 3: launch the agent.
  const exec = buildExecCommand({ agent, briefPath, vaultRoot })
  if (exec.note) console.log(term.dim(`note: ${exec.note}`))
  console.log(term.dim(`launching: ${exec.cmd} (brief=${briefPath})`))

  const child = spawn(exec.cmd, exec.args, {
    stdio: "inherit",
    cwd: vaultRoot,
    env: {
      ...process.env,
      TRIBE_NAME: slotRef,
      KM_AGENT_SLOT: slotRef,
      KM_VAULT_ROOT: vaultRoot,
    },
  })

  let cleanedUp = false
  const cleanup = (exitCode: number): void => {
    if (cleanedUp) return
    cleanedUp = true
    releaseSlot(repo, slotRef)
    tribeBroadcast(`released ${slotRef} (exit=${exitCode})`)
    process.exit(exitCode)
  }

  process.on("SIGINT", () => cleanup(130))
  process.on("SIGTERM", () => cleanup(143))
  child.on("error", (err) => {
    console.error(term.red(`failed to launch ${exec.cmd}: ${err.message}`))
    cleanup(1)
  })
  child.on("exit", (code) => {
    cleanup(code ?? 0)
  })
}
