#!/usr/bin/env bun

/**
 * Generate build-time information (git commit, build timestamp, etc.)
 *
 * This script should be run during the build process to embed version info
 * into the compiled code, avoiding expensive runtime git commands.
 *
 * Usage:
 * - Run during build: bun scripts/generate-build-info.ts
 * - Outputs to: packages/km-core/src/build-info.gen.ts
 *
 * The generated file exports:
 * - BUILD_TIME: ISO 8601 timestamp of build
 * - GIT_COMMIT: Short commit hash (7 chars) or "unknown"
 * - GIT_BRANCH: Current branch name or "unknown"
 * - VERSION: Package version from package.json
 * - GIT_DIRTY: Whether working directory has uncommitted changes
 *
 * Adapted from cloudi: ../cloudi/scripts/generate-build-info.ts
 */

import { execSync } from "node:child_process"
import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"

const PROJECT_ROOT = import.meta.dir + "/.."

/**
 * Get git information safely with fallbacks
 */
function getGitInfo() {
  let commit = "unknown"
  let branch = "unknown"
  let isDirty = false

  // Check env vars first (set by Docker ARG or CI)
  if (process.env.GIT_COMMIT) {
    commit = process.env.GIT_COMMIT.slice(0, 7)
  } else {
    try {
      commit = execSync("git rev-parse --short HEAD", {
        cwd: PROJECT_ROOT,
        encoding: "utf8",
        timeout: 5000,
        stdio: ["ignore", "pipe", "ignore"],
      })
        .trim()
        .slice(0, 7) // Ensure exactly 7 chars
    } catch {
      commit = "unknown"
    }
  }

  if (process.env.GIT_BRANCH) {
    branch = process.env.GIT_BRANCH
  } else {
    try {
      branch = execSync("git rev-parse --abbrev-ref HEAD", {
        cwd: PROJECT_ROOT,
        encoding: "utf8",
        timeout: 5000,
        stdio: ["ignore", "pipe", "ignore"],
      }).trim()
    } catch {
      branch = "unknown"
    }
  }

  try {
    const status = execSync("git status --porcelain", {
      cwd: PROJECT_ROOT,
      encoding: "utf8",
      timeout: 5000,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim()
    isDirty = status.length > 0
  } catch {
    // Can't determine, assume clean
    isDirty = false
  }

  return { commit, branch, isDirty }
}

/**
 * Get version from package.json
 */
function getVersion() {
  const packageJsonPath = join(PROJECT_ROOT, "package.json")
  const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8"))
  return packageJson.version
}

/**
 * Generate build info file
 */
function generateBuildInfo() {
  const buildTime = new Date().toISOString()
  const git = getGitInfo()
  const version = getVersion()

  const content = `/**
 * Auto-generated build information
 * Generated: ${buildTime}
 * DO NOT EDIT - this file is generated by scripts/generate-build-info.ts
 */

/** ISO 8601 timestamp of when the build was created */
export const BUILD_TIME = "${buildTime}"

/** Git commit hash (short form, 7 chars) */
export const GIT_COMMIT = "${git.commit}"

/** Current git branch name */
export const GIT_BRANCH = "${git.branch}"

/** Whether working directory had uncommitted changes at build time */
export const GIT_DIRTY = ${git.isDirty}

/** Package version from package.json */
export const VERSION = "${version}"

/**
 * Build information object
 */
export interface BuildInfo {
  buildTime: string
  gitCommit: string
  gitBranch: string
  gitDirty: boolean
  version: string
}

export const BUILD_INFO: BuildInfo = {
  buildTime: BUILD_TIME,
  gitCommit: GIT_COMMIT,
  gitBranch: GIT_BRANCH,
  gitDirty: GIT_DIRTY,
  version: VERSION,
}
`

  // Ensure directory exists
  const outputDir = join(PROJECT_ROOT, "packages/km-core/src")
  mkdirSync(outputDir, { recursive: true })

  const outputPath = join(outputDir, "build-info.gen.ts")
  writeFileSync(outputPath, content, "utf-8")

  console.log(`✅ Generated build info: ${outputPath}`)
  console.log(`   Version: ${version}`)
  console.log(`   Commit: ${git.commit}`)
  console.log(`   Branch: ${git.branch}`)
  console.log(`   Dirty: ${git.isDirty}`)
  console.log(`   Built: ${buildTime}`)
}

// Run if called directly
if (import.meta.main) {
  generateBuildInfo()
}
